### ISSUE TITLE
Make initial git commit

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#57]
## Summary

If we can, making an initial commit (or two) would help significantly for new projects. This is something that create-react-app does, and is a best practice for using git (it makes it clear what code was added by the generator, and gives developers a place to reset / rebase to).

**Comment by abhishekr700** [comment]
Hi, Could you explain this in a little more detail ? At what point do you want the commit to be made ?

**Comment by JRJurman** [comment]
The commit should be made after laying down all the files, similar to what create-react-app does. It should make any changes that users make after the generator step to be clear and obvious from git status / git diff

**Comment by abhishekr700** [comment]
I've figured that the generator.js is run when the `npx` command is executed. So you want the commit to be after the generation is complete i.e in the folder created after the generation step (where the generated project files exist)

**Comment by JRJurman** [comment]
@abhishekr700 yep!

**Comment by abhishekr700** [comment]
@JRJurman Okay looking into it. I replied on that PR have a look. Also, should I submit a PR for the bug with example-generate ?

**Comment by JRJurman** [comment]
I'm not aware of any bugs with example-generate, but please feel free to make a dedicated PR for it.

**Comment by abhishekr700** [comment]
@JRJurman I made a PR for the example-generate.
