### ISSUE TITLE
.gitignore becomes .npmignore on run

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#64]
## Summary

For some reason, the .gitignore file becomes an .npmignore file on running tram-one-express... Not sure why, or when this regression happened. 

This could be a documented feature of npm / node. Requires investigation.

**Comment by JRJurman** [comment]
This issue does not appear to happen when running the generate-example command in the project, only when running the `npx tram-one-express` command.

**Comment by chtinahow** [comment]
Similar  issue that was seen in this thread: https://github.com/npm/npm/issues/1862

**Comment by abhishekr700** [comment]
if there's a empty .npmignore, .gitignore would not be touched

**Comment by JRJurman** [comment]
@abhishekr700 after looking at the above issue, I'm not sure that's the case (also, I don't think we would actually want an empty one, rather something that is a copy of our existing gitignore). 

Where did you see that was the case (or do you have an example running where that is the case)?

**Comment by abhishekr700** [comment]
I read something similar here https://github.com/npm/npm/issues/3763

**Comment by JRJurman** [comment]
the latter comments (and the ones on the issue @chtinahow linked) seem to indicate that regardless of what files you have, all `.gitignore`s will be converted. if you have a working example though, that would be awesome!
