### ISSUE TITLE
Add xo configuration to generated projects

### ISSUE THREAD

**Issue by ethanjurman** [Tram-One/tram-one-express#65]
## Summary

To enforce best practices generated projects should use xo with the https://github.com/Tram-One/eslint-config-tram-one config.

**Comment by joevo2** [comment]
I'll like to work on this but need a bit more clarification. 

So this is not just adding an eslint and prettier config file but instead we will be using the xo pointing to https://github.com/Tram-One/eslint-config-tram-one along with prettier turn on with xo?

**Comment by joevo2** [comment]
Oh wait... the config is already there. https://github.com/Tram-One/tram-one-express/blob/66e1e058cf5c0d93a813e21fd9517ab0080c6359/package.json#L39-L43

So I just need to add the prettier?

**Comment by JRJurman** [comment]
@joevo2 actually, this project is a generator, and so the goal is to add prettier to projects that are generated with this. 

That being said, having prettier on this project is still worthwhile! Feel free to keep your initial PR and make an additional one for generated projects

**Comment by joevo2** [comment]
@JRJurman adding prettier include prettier the project itself right? So once we generate the project, we need to prettier the entire directory as well as adding an eslint and prettier config file?

**Comment by JRJurman** [comment]
@joevo2 running the project should generate a new project - you can see the README for example usage. That generated project should be configured with prettier / xo / eslint. 

It occurs to me that I may have misunderstood how eslint, prettier, and xo would work together. This may need to be investigated so that only one config is required.

**Comment by JRJurman** [comment]
@joevo2 @ethanjurman After some reading and becoming more familiar with the nuance between xo and prettier, I think they both solve the same issue, with different sets of configs. For this reason, I'm changing the ticket to simply include the xo and eslint config to the generated projects. 

@joevo2 If you'd like to make a brand new PR feel free to do so, or update your existing PR.

**Comment by abhishekr700** [comment]
Where is the eslint configuration you want to be included in the generated files?

**Comment by JRJurman** [comment]
@abhishekr700 the eslint config mentioned in the summary for the project, https://github.com/Tram-One/eslint-config-tram-one

**Comment by abhishekr700** [comment]
@JRJurman I opened a PR adding xo to generated files. Have a look if that is what you expected, so that I can move on to eslint configs

**Comment by abhishekr700** [comment]
@JRJurman Polite Bump ! :)

**Comment by JRJurman** [comment]
Completed in #72
