### ISSUE TITLE
Replace babel-polyfill with recommendations from babel

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#67]
## Summary

The babel-polyfill dependency has been deprecated, and it is now recommended to use specific other packages in its place (see https://babeljs.io/docs/en/babel-polyfill)

This should be a fairly easy fix. To Test, simply generate a project and try to use async await (a feature that I believe was failing without the polyfills).

**Comment by alirezamdv** [comment]
Hi, 
may i work on this ?! 
thanks

**Comment by JRJurman** [comment]
@alirezamdv feel free to pick this up! I'll leave this ticket open until a PR is merged in for the work.
If you have any questions, feel free to comment here or join our slack and DM me directly.
