### ISSUE TITLE
Add lint command to circle ci pipeline

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#75]
## Summary 

In #72 we introduced a lint command for generated projects. We should make sure that the generated project doesn't fail that check.

## Potential Implementation

In the package.json there are commands to run build and test on a generated app. We need to add a new `example-lint` script, and then add that to the existing circleci config.

**Comment by C3-TKO** [comment]
Isn't this already solved in master?

https://github.com/Tram-One/tram-one-express/blob/834bacfb8e67dc5a250f0bd4dc0eb641f7239705/.circleci/config.yml#L36

**Comment by JRJurman** [comment]
@C3-TKO actually, that runs the lint command on the `tram-one-express` project, it doesn't run it for the generated project. On that note, we'll probably want a `example-lint` script in the `package.json` that mimics the other npm scripts to run a script in the example project.
