### ISSUE TITLE
Move DevDependencies to Dependencies in template

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#76]
## Summary

Because we are building the template for web applications, the nuance for dev and normal dependencies doesn't actually matter. To make things clear and obvious, we should only have `dependencies`, and remove the `devDependencies` section.

## Potential Implementation

Copy and paste the lines from `devDependencies` section of the json and move them to the `dependencies` section. Remove the `devDependencies` section.

**Comment by quaj** [comment]
🤔

**Comment by quaj** [comment]
i don't know why but check #79, is it right?

**Comment by quaj** [comment]
ah sorry mistake "in template" :D

**Comment by quaj** [comment]
check #80 pls, is it right?
