### ISSUE TITLE
Move ColorHeader useState to custom hook

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#77]
## Summary

We should move the logic in the `ColorHeader.js` to a custom hook called `useColor`. This would be valuable for setting up a structure for other custom hooks.

## Interface

`useColor` should return an array, the current color, and increment color. It should call `useGlobalState` instead of `useState`, so that it returns a consistent value regardless of where it is called from. The key can be `APP_COLOR`. The logic in the hook should be otherwise similar to what's currently in `ColorHeader.js`.

```
const [color, incrementColor] = useColor()
```

## Folder Structure
Similar to the other components in the project, this should live in it's own folder with an index file that exposes the hook. There should also be an adjacent test file that validates the hook getter and setter. This hook should live in a `hooks` folder, next to components.

**Comment by Nfinger** [comment]
Ill take this if its still available

**Comment by JRJurman** [comment]
@nfinger it is! I'll close the ticket when a PR has been merged, so it's open for anyone until then

**Comment by Nfinger** [comment]
@JRJurman  https://github.com/Tram-One/tram-one-express/pull/82/files
