### ISSUE TITLE
Remove ./etc folder on install

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#8]
## Summary
Installing using the prefix flag seems to cause a `./etc` folder to be generated. It is empty, and should be removed, but I don't want to depend on the user having `rm` (which won't be the case on windows machines).

https://github.com/Tram-One/tram-one-express/blob/a29737c151e0e18dd56bd9fb94a7aca470e25c2d/generator.js#L50

## Checklist
- `./etc` folder should not be made (or should be cleaned up automatically) after running `tram-one-express`

**Comment by PSalant726** [comment]
Hey @JRJurman - I can take a crack at this.

The ghostly `etc` directory is a known issue with `npm install` when using the `--prefix` flag. I think we can work around it by including [`fs-extra`](https://www.npmjs.com/package/fs-extra) and using the `.remove` method.

I've opened PR #11 to address this. Let me know what you think!

**Comment by JRJurman** [comment]
Resolved by #11
