### ISSUE TITLE
support --no-install and --no-commit flags

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#86]
## Summary
It would be valuable for development (and possibly more specific scenarios) to be able to run the generator without triggering a commit or install. Currently we don't support any flags, but once we are able to parse them, it should be easy to wrap that logic in the generator with those checks (specifically the end of `generator.js`)

## Interface
We should support a flag `--no-commit` that prevents a commit from being made, and a flag `--no-install` that prevents doing an npm install. 
```
tram-one-express app-name [--no-commit] [--no-install]
```

## Potential Implementation
In the past we've used commander (https://www.npmjs.com/package/commander) for other projects. command-line-args (https://www.npmjs.com/package/command-line-args) also seems like a good alternative. Either should work for this use case.

**Comment by Joel-hanson** [comment]
Shall I take this up

**Comment by JRJurman** [comment]
@Joel-hanson feel free to work on it! I'll close the issue once a PR has been merged, otherwise it's up-for-grabs!
