### ISSUE TITLE
Output when making initial commit is not asynchronous 

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#87]
## Summary
Recently, a PR was merged that allowed us to create an initial commit on generating the project. For some reason, it appears that the output for the completion of the command can actually appear after our final logging. See here:
```
Initializing a git repository
Making the initial commit

Finished!
Navigate to 'tram-one-example', and run 'npm start' to get started!
Successfully created commit
```

Ideally we want the `Finished! Navigate to 'tram-one-example', and run 'npm start' to get started!` to be the last output, and `Making the initial commit` and `Successfully created commit` to happen one after the other. 

I don't know if this bug happens all the time.

## Potential Implementation
The logic for the git commit (and as an artifact, the entire generator logic) might need to be in an async function that awaits the resolution of the `simple-git` `commit` function. There may be easier alternative solutions. 

This logic lives at the end of `generator.js`

Alternatively, we can move the final logging after the commit (inside the commit callback), but the git logic will be conditionalized (and as an artifact, may not be called) in #86

**Comment by anusha5695** [comment]
Hi @JRJurman  I would like to pick this.

**Comment by anusha5695** [comment]
Hi @JRJurman : I have verified in my local. Works. Could you please check?
